export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const USER_PROFILE_FETCH_SUCCESS = "USER_PROFILE_FETCH_SUCCESS";
export const USER_PROFILE_FETCH_FAILURE = "USER_PROFILE_FETCH_FAILURE";
export const IS_LOADING = "IS_LOADING";
